// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQNfj6Z8fxQwbxgdDmPbLbialcm4cygMs',
    appId: '1:252478873856:web:b42092b291a9c11c9513e5',
    messagingSenderId: '252478873856',
    projectId: 'opponent-matching',
    authDomain: 'opponent-matching.firebaseapp.com',
    storageBucket: 'opponent-matching.appspot.com',
    measurementId: 'G-3Z5XE4E4ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDSRJSh3H2OxjBC3cFuedrA28BsF1D5KQ',
    appId: '1:252478873856:android:c345a60d0b8d8f789513e5',
    messagingSenderId: '252478873856',
    projectId: 'opponent-matching',
    storageBucket: 'opponent-matching.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWRZFPGLn-wtk4g9l0xbpMrW2xLxwIbLc',
    appId: '1:252478873856:ios:0abed8d626f591c39513e5',
    messagingSenderId: '252478873856',
    projectId: 'opponent-matching',
    storageBucket: 'opponent-matching.appspot.com',
    iosBundleId: 'com.example.opponentMatching',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWRZFPGLn-wtk4g9l0xbpMrW2xLxwIbLc',
    appId: '1:252478873856:ios:0abed8d626f591c39513e5',
    messagingSenderId: '252478873856',
    projectId: 'opponent-matching',
    storageBucket: 'opponent-matching.appspot.com',
    iosBundleId: 'com.example.opponentMatching',
  );
}
